project_name: xata
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -X main.GitCommit={{ .Commit }}
      - -X main.BuildDate={{ .Date }}
    goarch:
      - amd64
      - arm64
    goos:
      - linux
      - windows
      - darwin
    ignore:
      - goos: linux
        goarch: arm64
      - goos: windows
        goarch: arm64
archives:
  - replacements:
      amd64: x86_64
    files:
      - none* # package only the binary
    name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
gomod:
  # Proxy a module from proxy.golang.org, making the builds verifiable.
  # This will only be effective if running against a tag. Snapshots will ignore this setting.
  # Notice: for this to work your `build.main` must be a package, not a `.go` file.
  #
  # Default is false.
  # TODO enable once the repo is public
  proxy: false

  # If proxy is true, use these environment variables when running `go mod` commands (namely, `go mod tidy`).
  # Defaults to `os.Environ()`.
  env:
    - GOPROXY=https://proxy.golang.org,direct
    - GOSUMDB=sum.golang.org
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
